# Generated by Django 3.2.7 on 2024-04-25 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
