# Generated by Django 4.1 on 2024-04-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0004_alter_subscribing_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribing',
            old_name='subscribe',
            new_name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscribing',
            name='user',
        ),
    ]
