# Generated by Django 4.1 on 2024-04-29 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery_app', '0005_rename_subscribe_subscribing_subscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribing',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscribing',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
