# Generated by Django 4.1 on 2024-04-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery_app', '0006_remove_subscribing_subscriber_subscribing_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribing',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
